import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/security/authorization";
import { normalizeText,digitsOnly } from "@/lib/normalize";
import { handleRouteError } from "@/lib/http";
import { audit } from "@/modules/audit/service";
const rowSchema=z.object({type:z.string(),name:z.string().min(1),neighborhood:z.string().nullable().optional(),cep:z.string().nullable().optional(),latitude:z.number().nullable().optional(),longitude:z.number().nullable().optional(),status:z.string().optional()});
const schema=z.object({rows:z.array(rowSchema).max(5000)});
export async function POST(req:NextRequest){try{const u=await requirePermission('territory.import');const{rows}=schema.parse(await req.json());const setting=await prisma.systemSetting.findUniqueOrThrow({where:{key:'default_municipality_id'}});let created=0,skipped=0;await prisma.$transaction(async tx=>{for(const row of rows){if(row.status==='EXISTS'){skipped++;continue}const n=normalizeText(row.name);const t=row.type.toUpperCase();if(t.includes('RUA')||t==='STREET'){const street=await tx.street.upsert({where:{municipalityId_normalizedName:{municipalityId:setting.value,normalizedName:n}},update:{name:row.name,active:true,cep:row.cep?digitsOnly(row.cep):undefined,latitude:row.latitude,longitude:row.longitude},create:{municipalityId:setting.value,name:row.name,normalizedName:n,cep:row.cep?digitsOnly(row.cep):undefined,latitude:row.latitude,longitude:row.longitude}});if(row.neighborhood){const bn=normalizeText(row.neighborhood);const nb=await tx.neighborhood.findFirst({where:{municipalityId:setting.value,normalizedName:bn,active:true}});if(nb)await tx.streetNeighborhood.upsert({where:{streetId_neighborhoodId:{streetId:street.id,neighborhoodId:nb.id}},update:{},create:{streetId:street.id,neighborhoodId:nb.id}})}created++;continue}if(t.includes('RURAL')||t.includes('COMUNIDADE')||t==='RURAL_LOCALITY'){await tx.ruralLocality.upsert({where:{municipalityId_normalizedName:{municipalityId:setting.value,normalizedName:n}},update:{name:row.name,active:true,latitude:row.latitude,longitude:row.longitude},create:{municipalityId:setting.value,name:row.name,normalizedName:n,latitude:row.latitude,longitude:row.longitude,locationPrecision:'RURAL_LOCALITY'}});created++;continue}await tx.neighborhood.upsert({where:{municipalityId_normalizedName_type:{municipalityId:setting.value,normalizedName:n,type:'URBAN'}},update:{name:row.name,active:true,latitude:row.latitude,longitude:row.longitude},create:{municipalityId:setting.value,name:row.name,normalizedName:n,type:'URBAN',latitude:row.latitude,longitude:row.longitude}});created++;}});await audit({actorUserId:u.id,action:'IMPORT',entityType:'territory',changedFields:['records'],after:{created,skipped}});return NextResponse.json({created,skipped})}catch(e){return handleRouteError(e)}}
