"use client";
import { useMemo, useState } from "react";

type Trip = { id:string; title:string; startAt:string; endAt:string; origin:string; destination:string; status:string; vehicle?:string|null; driver?:string|null };
type View="day"|"week"|"month";
const fmt=(d:Date)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d);
const time=(d:Date)=>new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit"}).format(d);
function startOfDay(d:Date){const x=new Date(d);x.setHours(0,0,0,0);return x}
function endOfDay(d:Date){const x=new Date(d);x.setHours(23,59,59,999);return x}
function range(ref:Date,view:View){if(view==="day")return[startOfDay(ref),endOfDay(ref)] as const;if(view==="week"){const a=startOfDay(ref);const day=(a.getDay()+6)%7;a.setDate(a.getDate()-day);const b=endOfDay(a);b.setDate(b.getDate()+6);return[a,b] as const}const a=new Date(ref.getFullYear(),ref.getMonth(),1);const b=new Date(ref.getFullYear(),ref.getMonth()+1,0,23,59,59,999);return[a,b] as const}
export function FleetCalendar({trips}:{trips:Trip[]}){const[view,setView]=useState<View>("week");const[ref,setRef]=useState(()=>new Date());const[a,b]=range(ref,view);const visible=useMemo(()=>trips.filter(t=>new Date(t.startAt)<=b&&new Date(t.endAt)>=a).sort((x,y)=>+new Date(x.startAt)-+new Date(y.startAt)),[trips,a.getTime(),b.getTime()]);function move(dir:number){const n=new Date(ref);if(view==="day")n.setDate(n.getDate()+dir);else if(view==="week")n.setDate(n.getDate()+7*dir);else n.setMonth(n.getMonth()+dir);setRef(n)}return <div className="panel"><div className="page-head"><div><h2>Agenda</h2><p className="muted">{fmt(a)} a {fmt(b)}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="btn-ghost" onClick={()=>move(-1)}>Anterior</button><button className="btn-ghost" onClick={()=>setRef(new Date())}>Hoje</button><button className="btn-ghost" onClick={()=>move(1)}>Próximo</button><select value={view} onChange={e=>setView(e.target.value as View)} aria-label="Visualização da agenda"><option value="day">Dia</option><option value="week">Semana</option><option value="month">Mês</option></select></div></div><div style={{display:"grid",gap:10}}>{visible.map(t=><article key={t.id} style={{borderLeft:"4px solid #B51F2A",padding:"10px 14px",background:"#f7f7f7"}}><strong>{fmt(new Date(t.startAt))} · {time(new Date(t.startAt))}–{time(new Date(t.endAt))}</strong><div>{t.origin} → {t.destination}</div><div className="muted">{t.vehicle||"Veículo não definido"} · {t.driver||"Motorista não definido"}</div></article>)}{!visible.length&&<p className="muted">Nenhuma viagem neste período.</p>}</div></div>}
